services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_model
    ports:
      - "11434:11434"
    restart: unless-stopped
  
  embeddd:
    build:
      context: ./services/embeddd
      dockerfile: Dockerfile
    container_name: nomic_embed
    env_file:
      - .env
    ports:
      - "11500:11500"
    depends_on:
      - ollama  # not embedder
    restart: unless-stopped
